# Generated by Django 4.1.2 on 2023-02-03 19:20

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('active_players', models.ManyToManyField(related_name='active_players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
