# Generated by Django 4.1.2 on 2023-02-03 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_gameroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='cur_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.gameroom'),
        ),
    ]
