# Generated by Django 4.1.2 on 2023-02-03 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_state_cur_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='active_players',
            field=models.ManyToManyField(blank=True, null=True, related_name='active_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
