# Generated by Django 4.1.2 on 2023-02-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_state_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='old',
            field=models.BooleanField(default=False),
        ),
    ]
