# Generated by Django 4.1.2 on 2023-02-04 14:48

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_user_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='hash',
            field=models.CharField(blank=True, default=management.models.rand_string, max_length=100, unique=True),
        ),
    ]
