# Generated by Django 4.1.2 on 2023-02-04 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_gameroom_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='blue_team',
            field=models.ManyToManyField(blank=True, null=True, related_name='blue_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='red_team',
            field=models.ManyToManyField(blank=True, null=True, related_name='red_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
