# Generated by Django 4.1.2 on 2023-02-04 16:17

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_gameroom_blue_team_gameroom_red_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='blue_tree_xp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='map',
            field=models.JSONField(default=management.models.generate_game_map),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='red_tree_xp',
            field=models.FloatField(default=0),
        ),
    ]
