# Generated by Django 4.1.2 on 2023-02-04 16:18

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_gameroom_blue_tree_xp_gameroom_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='map',
            field=models.JSONField(blank=True, default=management.models.generate_game_map, null=True),
        ),
    ]
